// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/translator/translator.proto

package translator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TranslateRequest contains the text and language parameters for a translation call.
type TranslateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SourceLanguage string                 `protobuf:"bytes,2,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"`
	TargetLanguage string                 `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	Route          string                 `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_proto_translator_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_translator_translator_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *TranslateRequest) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *TranslateRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

// TranslateResponse contains the translated text and the provider that handled the request.
type TranslateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslatedText string                 `protobuf:"bytes,1,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_proto_translator_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_translator_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *TranslateResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_proto_translator_translator_proto protoreflect.FileDescriptor

const file_proto_translator_translator_proto_rawDesc = "" +
	"\n" +
	"!proto/translator/translator.proto\x12\n" +
	"translator\"\x8e\x01\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x0fsource_language\x18\x02 \x01(\tR\x0esourceLanguage\x12'\n" +
	"\x0ftarget_language\x18\x03 \x01(\tR\x0etargetLanguage\x12\x14\n" +
	"\x05route\x18\x04 \x01(\tR\x05route\"X\n" +
	"\x11TranslateResponse\x12'\n" +
	"\x0ftranslated_text\x18\x01 \x01(\tR\x0etranslatedText\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider2]\n" +
	"\x11TranslatorService\x12H\n" +
	"\tTranslate\x12\x1c.translator.TranslateRequest\x1a\x1d.translator.TranslateResponseB-Z+github.com/zoobz-io/cicero/proto/translatorb\x06proto3"

var (
	file_proto_translator_translator_proto_rawDescOnce sync.Once
	file_proto_translator_translator_proto_rawDescData []byte
)

func file_proto_translator_translator_proto_rawDescGZIP() []byte {
	file_proto_translator_translator_proto_rawDescOnce.Do(func() {
		file_proto_translator_translator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_translator_translator_proto_rawDesc), len(file_proto_translator_translator_proto_rawDesc)))
	})
	return file_proto_translator_translator_proto_rawDescData
}

var file_proto_translator_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_translator_translator_proto_goTypes = []any{
	(*TranslateRequest)(nil),  // 0: translator.TranslateRequest
	(*TranslateResponse)(nil), // 1: translator.TranslateResponse
}
var file_proto_translator_translator_proto_depIdxs = []int32{
	0, // 0: translator.TranslatorService.Translate:input_type -> translator.TranslateRequest
	1, // 1: translator.TranslatorService.Translate:output_type -> translator.TranslateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_translator_translator_proto_init() }
func file_proto_translator_translator_proto_init() {
	if File_proto_translator_translator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_translator_translator_proto_rawDesc), len(file_proto_translator_translator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translator_translator_proto_goTypes,
		DependencyIndexes: file_proto_translator_translator_proto_depIdxs,
		MessageInfos:      file_proto_translator_translator_proto_msgTypes,
	}.Build()
	File_proto_translator_translator_proto = out.File
	file_proto_translator_translator_proto_goTypes = nil
	file_proto_translator_translator_proto_depIdxs = nil
}
